### PR TITLE
Fix densification of ingots

### PR DESCRIPTION
**Pull request by tmathmeyer**
Also fix missing repo required for dependency "tritonus" used by
discord4j

### CODE REVIEW

**Comment by Jikoo** [comment]
Ingots and kelp are the entire reason the densificator exists, why would we remove half of its purpose?

**Comment by Jikoo** [comment]
Oh, I see, I was confused because you added an additional if statement instead of using an operator in the existing one.

If you want to do this, you should include all other stuff like rabbit leather -> leather, aka the reason I limited the densificator to blocks only in the first place.

**Comment by tmathmeyer** [comment]
I assumed you limited it to blocks because of boots passing the check for 4 of the same items? I just found it odd considering that the feature is advertised in game as crafting nuggets into ingots, but it won't currently do that.

Looks like the only other one is the rabbit hide: according to https://minecraft.gamepedia.com/Crafting#Complete_recipe_list
are there other custom ones enabled?

**Comment by Jikoo** [comment]
It was boots, yeah. Last I was aware in-game documentation specifically states it only compresses things into blocks. Mostly I don't want to move to a whitelist because it results in more work when more items are added, hard to test. Really this whole repo is a massive untested mess though, so who's counting.

I wouldn't be opposed to changing it to a boots check instead of occluding.

**Comment by tmathmeyer** [comment]
IMO a boots check is going to be worse, since there are more types of boots than there are [iron nug, gold nug, rabbit hide]. 

with the boots it's going to end up replacing the if (!occluding && !whitelisted) with a switch where the boots are cased and default does nothing

**Comment by tmathmeyer** [comment]
more descriptively - when netherite comes out, it'll be required to add netherite boots to a blacklist - which means that if it's forgotten, there will be some unhappy people with extra boots. OTOH, netherite blocks already pass the occlusion check, so no update would need to be made. If post-nether update we get more crafting items that might be unwanted but pass the 4/9/not-boots check, they will have to be added.

using a whitelist would at the very least not cause unwanted potentially un-reversable crafting operations to take place.

**Comment by Jikoo** [comment]
There are a couple workarounds for that. I'm out so I can't look now but I believe there is a Tag, the EquipmentSlot should also be a valid route, and worst case Enum.name().endsWith("_BOOTS") is a futureproof catch-all.

**Comment by tmathmeyer** [comment]
It also must prevent the crafting of Iron trap doors - hence the reliance on a whitelist for one-off things just seems more future proof.

also, in game: https://files.tedm.io/densdesc.png

**Comment by Jikoo** [comment]
Ah, the sign on the left contradicts the one on the right. That's an Ed thing, but we can work with it. True on the trapdoor front.

**Pull request merged**
